### ISSUE TITLE
Changing existing signatures can break existing libraries

### ISSUE THREAD

**Issue by FrankHassanabad** [alexfernandez/prototypes#12]
If using prototypes in a project and it overrides an existing behavior such as parseInt:

```
var shouldBeNaN = parseInt(undefined);
if isNaN(shouldBeNaN) {
  // This block never gets hit now
}
// I am now zero when before I wasn't.
```

This will cause 3rd party libraries to begin breaking in subtle ways.  Just letting you know.  I typically use lodash, underscore or other libraries for any additional needs rather than changing the overall Javascript system.

**Comment by alexfernandez** [comment]
This should be fixed in commit 135344c, and in version 0.4.3. Also added a test. Please reopen if still an issue!

The rationale to modify `parseInt()` is to avoid introducing subtle errors in the first place, like:

    parseInt(030) -> 24
