### ISSUE TITLE
prototypes version broke a project code in an incomprehensible way

### ISSUE THREAD

**Issue by superandrew** [alexfernandez/prototypes#18]
Hello, I'm not sure how to start to explain the problem I am having. I am running a complicated coffee project which depends on many npm modules. One of those is microprofiler. Microprofiler specifies a dependency to prototypes as "*" such as any new change in prototype gets incorporated in microprofiler.

I don't know exactly if this problem is related to prototypes, to microprofiler or at all if it is a problem that belong to code, however I'll show the problematic lines, with the hope that will help understanding the problem.

I get this error:

```
mixins.coffee:117:5: error: the variable "query" can't be assigned with ?= because it has not been declared before
    query ?= {}
    ^^^^^

```

then the code where this is happening

```query: (
    context
    collection
    params = {}
  ) ->
    {query, options, game_id, version} = params
    query ?= {}
    options ?= {}
    if game_id? then query.game_id = game_id
    if version? then query.version = version
    # TODO: Throw error when game/version does not exist
    collection.find(query, options).toArray()

```

Any Idea that pops to mind?

Simply replacing the prototype module with the one of a couple of weeks ago makes the error disappear.

**Comment by alexfernandez** [comment]
Weird! Which version number is working for you? The only [change](https://github.com/alexfernandez/prototypes/commits/master) was a couple of version bumps and a change in escaping.

**Comment by superandrew** [comment]
well, I try to explain it the best I can.

My project is using the microprofiler module, which has this package.json:


```!json
{
  "name": "microprofiler",
  "version": "0.1.1",
  "description": "Low-level profiling for node.js: squeeze those microseconds.",
  "homepage": "https://github.com/alexfernandez/microprofiler",
  "contributors": [
    {
      "name": "Alex Fernández",
      "email": "alexfernandeznpm@gmail.com"
    }
  ],
  "license": "MIT",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/alexfernandez/microprofiler"
  },
  "dependencies": {
    "prototypes": "*",
    "testing": "*",
    "log": "*"
  },
  "keywords": [
    "profiler",
    "profiling",
    "microprofiler",
    "microseconcds",
    "npm",
    "optimization"
  ],
  "engines": {
    "node": "*"
  },
  "scripts": {
    "test": "node test.js"
  },
  "private": false,
  "bugs": {
    "url": "https://github.com/alexfernandez/microprofiler/issues"
  },
  "_id": "microprofiler@0.1.1",
  "dist": {
    "shasum": "d96ddfa1204b1ea31424b909e3479698428718e2",
    "tarball": "https://registry.npmjs.org/microprofiler/-/microprofiler-0.1.1.tgz"
  },
  "_from": "microprofiler@>=0.1.1 <0.2.0",
  "_npmVersion": "1.3.24",
  "_npmUser": {
    "name": "alexfernandez",
    "email": "alexfernandeznpm@gmail.com"
  },
  "maintainers": [
    {
      "name": "alexfernandez",
      "email": "alexfernandeznpm@gmail.com"
    }
  ],
  "directories": {},
  "_shasum": "d96ddfa1204b1ea31424b909e3479698428718e2",
  "_resolved": "https://registry.npmjs.org/microprofiler/-/microprofiler-0.1.1.tgz"
}

```

Now, what happens:

in the normal case, inside the node_modules of microprofiler, there is prototypes version 2.0.0. This normal version was retrieved from npm around november/december 2016.

In the "broken" version npm is resolving version 2.3.2 of the same library.

The only change I can see is this:

object.js has this addition:

```
newObject.hasProperties = function()
{
	for (var key in this)
	{
		if (this.hasOwnProperty(key))
		{
			return true;
		}
	}
	return false;
}

```
this is the breaking code, and I can see probably why, as it seems to redefine the hasProperties function, but honestly I don't know if this is correct.

This other change doesn't influence the code:
string.js
![screen shot 2017-03-23 at 15 26 44](https://cloud.githubusercontent.com/assets/71364/24252286/51c11f0c-0fdd-11e7-9674-392e4761a524.jpg)

Now I am considering fixing the npm dependencies, or forking this repository in a way that fixes the dependencies of prototypes and testing. Do you have an idea on how this is happening and which is the best way to fix it?

Thanks

**Comment by alexfernandez** [comment]
For now you can just fix the dependency for `prototypes` and send a PR, I will merge it. Hopefully I can look into it soon. Thanks!

**Comment by superandrew** [comment]
ok, so I'm going to fork microprofiler, test it and then send you a PR!

Thanks!

**Comment by alexfernandez** [comment]
That will be great!

**Comment by alexfernandez** [comment]
Hi again, I am updating the dependencies on microprofiler. If this is still giving you grief please pin the version for microprofiler at 1.0.1. Thanks!
