### ISSUE TITLE
require(prototypes) throws error

### ISSUE THREAD

**Issue by Gattermeier** [alexfernandez/prototypes#7]
I am getting an error thrown just by require('prototypes');

TypeError: Object function (element)
{
	if (!element)
	{
		return undefined;
	}
	var index = this.indexOf(element);
	if (index == -1)
	{
		return undefined;
	}
	var removed = this.splice(index, 1);
	return removed[0];
} has no method 'push'

**Comment by alexfernandez** [comment]
Any more info? Node version, os?

**Comment by Gattermeier** [comment]
Node v0.10.28
Running on Mac OSX 10.10.1

**Comment by alexfernandez** [comment]
Hi, any news on this issue?

**Comment by alexfernandez** [comment]
Closing, please reopen if still an issue.
